### ISSUE TITLE
docker-php-ext-install not working

### ISSUE THREAD

**Issue by daniel-halito** [ignaciolflores/docker-php-5.3#1]
Hello,

For some reason i'm not able to install PHP extensions using `docker-php-ext-install`
I keep getting the following message "No such file or directory".

Any idea what it could be? 

Thanks for keeping this alive, even to this day people need PHP 5.3 :()

**Comment by ignaciolflores** [comment]
Hi! Thanks for asking, it also help to keep this alive.
In order to get docker-php-ext-install working, the extension you want to install has to be in /usr/src/php/ext/

For example, if you want to instal curl, you just have to write
```bash
docker-php-ext-configure curl
docker-php-ext-install curl
docker-php-ext-enable curl
```

**Comment by daniel-halito** [comment]
Works great! Muchas gracias! ;)
